// <auto-generated />
namespace LoginRegister.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addingmodelmaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingmodelmaster));
        
        string IMigrationMetadata.Id
        {
            get { return "201909290608207_addingmodelmaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
